require("nvim-treesitter.configs").setup({
  ensure_installed = {
    "astro",
    "c",
    "clojure",
    "cpp",
    "css",
    "elixir",
    "go",
    "html",
    "json",
    "java",
    "javascript",
    "lua",
    "nix",
    "rust",
    "scss",
    "svelte",
    "toml",
    "tsx",
    "typescript",
    "yaml",
    "zig",
  },
  sync_installed = false,
  auto_install = false,
  highlight = {
    enable = true,
  },
  additional_vim_regex_highlightling = false,
})
