ln -s ~/developer/dotfiles/alpine/config/zsh/.zshrc ~/.zshrc
ln -s ~/developer/dotfiles/alpine/config/bat/config ~/.config/bat/config
ln -s ~/developer/dotfiles/alpine/config/bat/themes ~/.config/bat/
ln -s ~/developer/dotfiles/alpine/config/emacs/init.el ~/.config/emacs/init.el
ln -s ~/developer/dotfiles/alpine/config/nvim/init.lua ~/.config/nvim/init.lua
ln -s ~/developer/dotfiles/alpine/config/nvim/after ~/.config/nvim/
ln -s ~/developer/dotfiles/alpine/config/nvim/lua ~/.config/nvim/
ln -s ~/developer/dotfiles/alpine/config/starship/starship.toml ~/.config/starship/starship.toml
ln -s ~/developer/dotfiles/alpine/config/tmux/tmux.conf ~/.config/tmux/tmux.conf
