tap "dart-lang/dart"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "sass/sass"
brew "bat"
brew "coreutils"
brew "deno"
brew "exa"
brew "fd"
brew "webp"
brew "gopls"
brew "httpd"
brew "lf"
brew "mariadb"
brew "mongosh"
brew "mosh"
brew "neovim", args: ["HEAD"]
brew "php"
brew "ripgrep"
brew "uutils-coreutils", link: false
brew "sass/sass/sass"
cask "kitty"
