add_newline = false

format = """
$username\
$shlvl\
$singularity\
$kubernetes\
$directory\
$hostname\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$cobol\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$lua\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$pulumi\
$purescript\
$python\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$cmd_duration\
$line_break\
$jobs\
$battery\
$time\
$status\
$shell\
$character"""

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)' 
vicmd_symbol = '[➜](bold purple)'

[hostname]
ssh_only = false
format = 'on [$hostname](bold blue) '
trim_at = '.'
disabled = false

[username]
style_user = 'yellow bold'
style_root = 'red bold'
format = '[$user]($style) '
disabled = false
show_always = true

[directory]
format = 'in [$path](bold cyan) '

[nodejs]
symbol = '⬢ '

[package]
format = 'is [$version](bold red) '

