# Typescript Configuration

---
name: TypeScript
windows:
  - tabs:
      - title: TypeScript
        layout:
          split_direction: horizontal
          panes:
            - split_direction: vertical
              panes:
                - cwd: /Users/matt/Developer/sandbox/typescript
                  commands:
                    - exec: vi index.ts
                - cwd: /Users/matt/Developer/sandbox/typescript
                  commands:
                    - exec: yarn watch
            - split_direction: vertical
              panes:
                - cwd: /Users/matt/Developer/sandbox/typescript
                  commands:
                    - exec: vi index.test.ts
                - cwd: /Users/matt/Developer/sandbox/typescript
                  commands:
                    - exec: yarn test
