# Go Launch Configuration

---
name: Go
windows:
  - tabs:
      - title: Go
        layout:
          split_direction: horizontal
          panes:
            - split_direction: vertical
              panes:
                - cwd: /Users/matt/Developer/sandbox/go
                  commands:
                    - exec: vi main.go
                - cwd: /Users/matt/Developer/sandbox/go
                  commands:
                    - exec: air
            - split_direction: vertical
              panes:
                - cwd: /Users/matt/Developer/sandbox/go
                  commands:
                    - exec: vi main_test.go
                - cwd: /Users/matt/Developer/sandbox/go
                  commands:
                    - exec: gotdd
